# -*- coding: utf-8 -*-
"""abc_feature_selection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sq0TcwItL-gEXIO14IgQKyCCIViROJFI
"""

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import warnings
warnings.filterwarnings("ignore")

from sklearn.datasets import load_breast_cancer
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score, StratifiedKFold

# =========================
# DATASET
# =========================
data = load_breast_cancer()
X_raw = data.data
y = data.target
feat_names = data.feature_names

scaler = StandardScaler()
X = scaler.fit_transform(X_raw)

n_samples, n_features = X.shape

# =========================
# INICIALIZACIÓN
# =========================
def initialize_population(n_bees, n_features, seed=42):
    rng = np.random.default_rng(seed)
    population = rng.integers(0, 2, size=(n_bees, n_features))
    for i in range(n_bees):
        if population[i].sum() == 0:
            population[i, rng.integers(0, n_features)] = 1
    return population

# =========================
# FITNESS
# =========================
def fitness_function(solution, X, y, alpha=0.88, beta=0.12):
    if solution.sum() == 0:
        return 0.0

    X_subset = X[:, solution == 1]

    clf = RandomForestClassifier(n_estimators=50, random_state=42, n_jobs=-1)
    cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

    scores = cross_val_score(clf, X_subset, y, cv=cv, scoring="accuracy")
    accuracy = scores.mean()

    penalty = solution.sum() / len(solution)
    return alpha * accuracy - beta * penalty

# =========================
# VECINO
# =========================
def generate_neighbor(solution, rng):
    neighbor = solution.copy()
    idx = rng.integers(0, len(solution))
    neighbor[idx] = 1 - neighbor[idx]

    if neighbor.sum() == 0:
        neighbor[idx] = 1

    return neighbor

# =========================
# FASES ABC
# =========================
def employed_phase(pop, fitness, trials, X, y, rng, alpha, beta):
    for i in range(len(pop)):
        neighbor = generate_neighbor(pop[i], rng)
        fit = fitness_function(neighbor, X, y, alpha, beta)

        if fit > fitness[i]:
            pop[i] = neighbor
            fitness[i] = fit
            trials[i] = 0
        else:
            trials[i] += 1
    return pop, fitness, trials


def onlooker_phase(pop, fitness, trials, X, y, rng, alpha, beta):
    probs = fitness / fitness.sum() if fitness.sum() != 0 else np.ones(len(pop)) / len(pop)

    for _ in range(len(pop)):
        i = rng.choice(len(pop), p=probs)
        neighbor = generate_neighbor(pop[i], rng)
        fit = fitness_function(neighbor, X, y, alpha, beta)

        if fit > fitness[i]:
            pop[i] = neighbor
            fitness[i] = fit
            trials[i] = 0
        else:
            trials[i] += 1
    return pop, fitness, trials


def scout_phase(pop, fitness, trials, X, y, rng, limit, alpha, beta):
    for i in range(len(pop)):
        if trials[i] >= limit:
            new = rng.integers(0, 2, size=len(pop[i]))
            if new.sum() == 0:
                new[rng.integers(0, len(new))] = 1

            pop[i] = new
            fitness[i] = fitness_function(new, X, y, alpha, beta)
            trials[i] = 0
    return pop, fitness, trials

# =========================
# ALGORITMO PRINCIPAL
# =========================
def run_abc(X, y, n_bees=30, max_iter=100, limit=20, alpha=0.88, beta=0.12, seed=42):
    rng = np.random.default_rng(seed)

    pop = initialize_population(n_bees, X.shape[1], seed)
    fitness = np.array([fitness_function(sol, X, y, alpha, beta) for sol in pop])
    trials = np.zeros(n_bees)

    best_idx = np.argmax(fitness)
    best_sol = pop[best_idx].copy()
    best_fit = fitness[best_idx]

    history = []

    for _ in range(max_iter):
        pop, fitness, trials = employed_phase(pop, fitness, trials, X, y, rng, alpha, beta)
        pop, fitness, trials = onlooker_phase(pop, fitness, trials, X, y, rng, alpha, beta)
        pop, fitness, trials = scout_phase(pop, fitness, trials, X, y, rng, limit, alpha, beta)

        idx = np.argmax(fitness)
        if fitness[idx] > best_fit:
            best_fit = fitness[idx]
            best_sol = pop[idx].copy()

        history.append(best_fit)

    return best_sol, best_fit, history

# =========================
# EJECUCIÓN
# =========================
best_solution, best_fitness, history = run_abc(X, y)

selected_indices = np.where(best_solution == 1)[0]

print("Fitness:", best_fitness)
print("N features:", len(selected_indices))

# =========================
# GRÁFICA
# =========================
plt.plot(history)
plt.title("Convergencia ABC")
plt.xlabel("Iteraciones")
plt.ylabel("Fitness")
plt.grid()
plt.show()