# -*- coding: utf-8 -*-
"""Clustering_Gruber.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ayhoje5rmX4u3d1omEteh3F7gjRshEFX
"""

# =============================================================================
# PSO-Clustering — Actividad 03 (Ítem d)
# Curso   : Aprendizaje de Máquina — 2026-I
# Autor   : GRUBER COAQUIRA, Gian Carlos
# Dataset : Wisconsin Breast Cancer Diagnostic (WBCD)
# =============================================================================

import numpy as np
import pandas as pd
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

from sklearn.preprocessing   import StandardScaler, LabelEncoder
from sklearn.metrics         import (silhouette_score,
                                     adjusted_rand_score,
                                     davies_bouldin_score)
from sklearn.cluster         import KMeans
from sklearn.decomposition   import PCA

np.random.seed(42)

# =============================================================================
# 1. CARGA Y PREPROCESAMIENTO
# =============================================================================
print("=" * 60)
print("  PSO-Clustering — Dataset WBCD")
print("=" * 60)

df = pd.read_csv('dataset/data.csv')
df.drop(columns=['id', 'Unnamed: 32'], inplace=True, errors='ignore')

le     = LabelEncoder()
y_true = le.fit_transform(df['diagnosis'].values)   # M=1, B=0
X_raw  = df.drop(columns=['diagnosis']).values

scaler = StandardScaler()
X      = scaler.fit_transform(X_raw)                # (569, 30)

n_samples, D = X.shape   # 569, 30
K            = 2          # clusters

print(f"\n  Instancias : {n_samples}")
print(f"  Features   : {D}")
print(f"  Clusters K : {K}")
print(f"  Malignos   : {(y_true==1).sum()}  |  Benignos: {(y_true==0).sum()}")

# =============================================================================
# 2. FUNCIÓN DE APTITUD (FITNESS) — SSE vectorizado
# =============================================================================
def fitness(particle, X, K, D):
    """Suma de Distancias Cuadráticas Intra-Cluster (SSE). Minimizar."""
    centroids = particle.reshape(K, D)
    # distancias de cada punto a cada centroide: shape (n, K)
    dists = np.linalg.norm(X[:, None, :] - centroids[None, :, :], axis=2)
    return float(np.sum(np.min(dists, axis=1) ** 2))

def assign_clusters(X, centroids):
    """Asignar cada punto al centroide más cercano."""
    dists  = np.linalg.norm(X[:, None, :] - centroids[None, :, :], axis=2)
    return np.argmin(dists, axis=1)

# =============================================================================
# 3. INICIALIZACIÓN DEL ENJAMBRE
# =============================================================================
n_particles = 30
max_iter    = 200
w_max, w_min = 0.9, 0.4
c1, c2       = 2.0, 2.0
v_max        = 0.5 * (X.max() - X.min())

x         = np.zeros((n_particles, K * D))
v         = np.zeros((n_particles, K * D))
pbest     = np.zeros((n_particles, K * D))
pbest_fit = np.full(n_particles, np.inf)

print("\n  Inicializando enjambre...")
for i in range(n_particles):
    idx       = np.random.choice(n_samples, size=K, replace=False)
    x[i]      = X[idx].flatten()           # centroides iniciales = puntos reales
    v[i]      = np.zeros(K * D)
    pbest[i]  = x[i].copy()
    pbest_fit[i] = fitness(x[i], X, K, D)

gbest_idx = np.argmin(pbest_fit)
gbest     = pbest[gbest_idx].copy()
gbest_fit = pbest_fit[gbest_idx]

print(f"  SSE inicial (mejor partícula): {gbest_fit:.4f}")

# =============================================================================
# 4. CICLO PRINCIPAL PSO
# =============================================================================
print("\n  Ejecutando PSO...\n")
history_sse  = [gbest_fit]
conv_iter    = max_iter

for iteration in range(max_iter):
    w = w_max - (w_max - w_min) * (iteration / max_iter)   # inercia decreciente

    for i in range(n_particles):
        r1 = np.random.rand(K * D)
        r2 = np.random.rand(K * D)

        # Actualización de velocidad
        v[i] = (w  * v[i]
              + c1 * r1 * (pbest[i] - x[i])
              + c2 * r2 * (gbest    - x[i]))

        # Clamping de velocidad
        v[i] = np.clip(v[i], -v_max, v_max)

        # Actualización de posición
        x[i] = x[i] + v[i]

        # Evaluar nueva posición
        score = fitness(x[i], X, K, D)

        # Actualizar pbest
        if score < pbest_fit[i]:
            pbest[i]     = x[i].copy()
            pbest_fit[i] = score

        # Actualizar gbest
        if score < gbest_fit:
            gbest     = x[i].copy()
            gbest_fit = score

    history_sse.append(gbest_fit)

    # Log cada 20 iteraciones
    if (iteration + 1) % 20 == 0:
        print(f"  Iter {iteration+1:3d}/{max_iter}  |  SSE: {gbest_fit:.4f}  |  w: {w:.3f}")

    # Convergencia anticipada
    if iteration > 15:
        mejora = abs(history_sse[-16] - history_sse[-1])
        if mejora < 1e-6:
            conv_iter = iteration + 1
            print(f"\n  ✓ Convergencia anticipada en iteración {conv_iter}")
            break

# =============================================================================
# 5. RESULTADOS FINALES — PSO
# =============================================================================
best_centroids = gbest.reshape(K, D)
labels_pso     = assign_clusters(X, best_centroids)

sil_pso = silhouette_score(X, labels_pso)
db_pso  = davies_bouldin_score(X, labels_pso)
ari_pso = adjusted_rand_score(y_true, labels_pso)

print("\n" + "=" * 60)
print("  RESULTADOS — PSO-Clustering")
print("=" * 60)
print(f"  SSE Final               : {gbest_fit:.4f}")
print(f"  Silhouette Score        : {sil_pso:.4f}")
print(f"  Davies-Bouldin Index    : {db_pso:.4f}")
print(f"  Adjusted Rand Index     : {ari_pso:.4f}")
print(f"  Iteraciones ejecutadas  : {conv_iter}")
print(f"  Cluster 0 → {(labels_pso==0).sum()} puntos  |  Cluster 1 → {(labels_pso==1).sum()} puntos")

# =============================================================================
# 6. COMPARATIVA CON K-MEANS
# =============================================================================
km = KMeans(n_clusters=K, n_init=20, random_state=42)
km.fit(X)
labels_km = km.labels_

sil_km = silhouette_score(X, labels_km)
db_km  = davies_bouldin_score(X, labels_km)
ari_km = adjusted_rand_score(y_true, labels_km)

print("\n" + "=" * 60)
print("  COMPARATIVA — PSO vs K-Means")
print("=" * 60)
print(f"  {'Métrica':<28}  {'PSO':>10}  {'K-Means':>10}")
print(f"  {'-'*50}")
print(f"  {'SSE (Inertia)':<28}  {gbest_fit:>10.4f}  {km.inertia_:>10.4f}")
print(f"  {'Silhouette Score':<28}  {sil_pso:>10.4f}  {sil_km:>10.4f}")
print(f"  {'Davies-Bouldin Index':<28}  {db_pso:>10.4f}  {db_km:>10.4f}")
print(f"  {'Adjusted Rand Index':<28}  {ari_pso:>10.4f}  {ari_km:>10.4f}")

# =============================================================================
# 7. VISUALIZACIONES (guardadas como PNG)
# =============================================================================
pca = PCA(n_components=2, random_state=42)
X2  = pca.fit_transform(X)
var_exp = pca.explained_variance_ratio_

fig, axes = plt.subplots(1, 3, figsize=(18, 5))
fig.suptitle("PSO-Clustering — Dataset WBCD", fontsize=14, fontweight='bold')

# ── Gráfica 1: Convergencia SSE ──────────────────────────────────────────────
axes[0].plot(history_sse, color='steelblue', linewidth=2)
axes[0].set_title("Convergencia del SSE — PSO", fontweight='bold')
axes[0].set_xlabel("Iteración")
axes[0].set_ylabel("SSE")
axes[0].grid(True, alpha=0.3)
axes[0].axhline(km.inertia_, color='red', linestyle='--', label=f'K-Means SSE: {km.inertia_:.1f}')
axes[0].legend()

# ── Gráfica 2: Clusters PSO (PCA 2D) ─────────────────────────────────────────
colors_pso = ['#2E75B6', '#ED7D31']
for k in range(K):
    mask = labels_pso == k
    axes[1].scatter(X2[mask, 0], X2[mask, 1], c=colors_pso[k],
                    label=f'Cluster {k} (n={mask.sum()})', alpha=0.6, s=30, edgecolors='none')

# Centroides proyectados
cent_2d = pca.transform(best_centroids)
axes[1].scatter(cent_2d[:, 0], cent_2d[:, 1], c='black', marker='X',
                s=200, zorder=5, label='Centroides PSO')
axes[1].set_title(f"Clusters PSO (PCA 2D)\nVar. explicada: {sum(var_exp)*100:.1f}%", fontweight='bold')
axes[1].set_xlabel(f"PC1 ({var_exp[0]*100:.1f}%)")
axes[1].set_ylabel(f"PC2 ({var_exp[1]*100:.1f}%)")
axes[1].legend(fontsize=8)
axes[1].grid(True, alpha=0.3)

# ── Gráfica 3: Etiquetas reales (M/B) ────────────────────────────────────────
colors_real = ['#70AD47', '#C00000']
labels_real = ['Benigno (B)', 'Maligno (M)']
for k in range(K):
    mask = y_true == k
    axes[2].scatter(X2[mask, 0], X2[mask, 1], c=colors_real[k],
                    label=labels_real[k], alpha=0.6, s=30, edgecolors='none')
axes[2].set_title("Distribución Real (PCA 2D)\nM = Maligno | B = Benigno", fontweight='bold')
axes[2].set_xlabel(f"PC1 ({var_exp[0]*100:.1f}%)")
axes[2].set_ylabel(f"PC2 ({var_exp[1]*100:.1f}%)")
axes[2].legend(fontsize=8)
axes[2].grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig('pso_clustering_resultados.png', dpi=150, bbox_inches='tight')
print("\n  ✓ Gráfica guardada: pso_clustering_resultados.png")
print("\n  Listo.")