# -*- coding: utf-8 -*-
"""Hyperparameter Tuning con PSO J

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a46iP7FYZo6d-sOn56xEyCed1zXih2vi
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_wine
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier

plt.style.use('dark_background')

np.random.seed(42)

data = load_wine()
X = data.data
y = data.target

def fitness(particle):
    n_estimators = int(particle[0])
    max_depth = int(particle[1])

    n_estimators = max(10, n_estimators)
    max_depth = max(1, max_depth)

    model = RandomForestClassifier(
        n_estimators=n_estimators,
        max_depth=max_depth,
        random_state=42
    )

    score = cross_val_score(model, X, y, cv=5).mean()
    return score

num_particles = 20
dimensions = 2
iterations = 30

w = 0.8
c1 = 2
c2 = 2

particles = np.random.uniform(
    low=[10, 1],
    high=[300, 30],
    size=(num_particles, dimensions)
)

velocities = np.random.uniform(-5, 5, (num_particles, dimensions))

pbest = particles.copy()
pbest_scores = np.array([fitness(p) for p in particles])

gbest = pbest[np.argmax(pbest_scores)].copy()
gbest_score = np.max(pbest_scores)

history_best = []
history_avg = []
history_n = []
history_d = []

for iteration in range(iterations):

    for i in range(num_particles):

        r1 = np.random.rand(dimensions)
        r2 = np.random.rand(dimensions)

        velocities[i] = (
            w * velocities[i]
            + c1 * r1 * (pbest[i] - particles[i])
            + c2 * r2 * (gbest - particles[i])
        )

        particles[i] += velocities[i]

        particles[i][0] = np.clip(particles[i][0], 10, 300)
        particles[i][1] = np.clip(particles[i][1], 1, 30)

        score = fitness(particles[i])

        if score > pbest_scores[i]:
            pbest[i] = particles[i].copy()
            pbest_scores[i] = score

    best_idx = np.argmax(pbest_scores)

    if pbest_scores[best_idx] > gbest_score:
        gbest = pbest[best_idx].copy()
        gbest_score = pbest_scores[best_idx]

    history_best.append(gbest_score)
    history_avg.append(np.mean(pbest_scores))
    history_n.append(gbest[0])
    history_d.append(gbest[1])

    print(f"Iteración {iteration+1}: Mejor Accuracy = {gbest_score:.4f}")

print("\n===== MEJORES HIPERPARÁMETROS =====")
print("n_estimators =", int(gbest[0]))
print("max_depth =", int(gbest[1]))
print("Accuracy final =", round(gbest_score, 4))

plt.figure(figsize=(10,6))

plt.plot(history_best, label="Mejor (gbest)", linewidth=2)
plt.plot(history_avg, label="Promedio", linestyle="--")

plt.xlabel("Iteraciones")
plt.ylabel("Accuracy")
plt.title("Evolución del PSO")
plt.legend()
plt.grid(alpha=0.3)

plt.show()

plt.figure(figsize=(10,6))

plt.plot(history_n, label="n_estimators")
plt.plot(history_d, label="max_depth")

plt.xlabel("Iteraciones")
plt.ylabel("Valor")
plt.title("Evolución de Hiperparámetros")
plt.legend()
plt.grid(alpha=0.3)

plt.show()


plt.figure(figsize=(10,6))

plt.scatter(
    [p[0] for p in pbest],
    [p[1] for p in pbest]
)

plt.xlabel("n_estimators")
plt.ylabel("max_depth")
plt.title("Distribución Final del Enjambre")
plt.grid(alpha=0.3)

plt.show()